### ISSUE TITLE
Copy-past readme example does not work 

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/setup-tarantool#13]
If I copypaste readme instructions `tarantoolctl rocks install luatest`
```
Error: Build error: 'cmake' program not found. Make sure CMake is installed and is available in your PATH (or you may want to edit the 'variables.CMAKE' value in file '/etc/tarantool/rocks/config-5.1.lua')
17
Error: Process completed with exit code 1.
```

This way cmake setup is needed.

Or specify luatest version to install binary package: for eg `tarantoolctl rocks install luatest 0.5.2`

**Comment by rosik** [comment]
We don't support self-hosted runners yet, see #11.
In your case, I suggest installing cmake manually.
